### ISSUE TITLE
Test Server Install

### ISSUE THREAD

**Issue by Roaban** [BigBenMOTO/DesolationREDUX#1]
Hi guys been following only for a few days, but what i see so far looks truly amazing.
I have decided to try and install the github files on our test server, however, i seem to have run into some troubles.

I have the server files installed, also the client files, what i am having trouble with i believe is the Arma 3 Extension i have filled in the DB info but I am unsure of what do to with this folder. any help would be appreciated.
This is the error i am getting:

Mission file: Desolation (__cur_mp)
Mission world: Tanoa
Mission directory: mpmissions\__cur_mp.Tanoa\
No more slot to add connection at 015030 (1523.6,3012.8)
Attempt to override final function - base_clientfunctions_list
Attempt to override final function - base_serverfunctions_list
Attempt to override final function - bis_functions_list
Attempt to override final function - bis_functions_listpreinit
Attempt to override final function - bis_functions_listpostinit
Attempt to override final function - bis_functions_listrecompile
Attempt to override final function - bis_fnc_missionflow
"<PluginManager>: Preinit Called"
"<PluginManager>: Broadcasted 117 functions"
"""{'dllFunction': 'iocall', 'dllArguments': { 'extFunction': 'GetInitOrder', 'extArguments': { } } }"""
"{'dllFunction': 'iocall', 'dllArguments': { 'extFunction': 'GetCfgFile', 'extArguments': { 'configfiles': '' } } }"
Error in expression <ject setVariable _x;
} forEach _data;
} forEach _initOrder;

>
Error position: <forEach _initOrder;

>
Error foreach: Type String, expected Array
File PluginManager\Functions\fn_compileCfg.sqf, line 33
Error in expression <ject setVariable _x;
} forEach _data;
} forEach _initOrder;

>
Error position: <forEach _initOrder;

>
Error Generic error in expression
File PluginManager\Functions\fn_compileCfg.sqf, line 33
Connected to Steam servers
c:\w\stable\futura\lib\network\networkserver.cpp NetworkServer::OnClientStateChanged:NOT IMPLEMENTED - briefing!
Mission id: a7ae1d5e3d8d3550239c901445f5f256e77fe8dd

**Comment by Legodev** [comment]
The mod is not ready to use yet, there will be no support until the mod entered public alpha.

But to answer your question, you need to compile the Arma 3 Extension your self, I will not send out any pre compiled files until we entered public alpha.

**Comment by Roaban** [comment]
ok ty for reply i will wait patiently :)
